"""add statuse of offers

Revision ID: 21f393c5deee
Revises: d8bebe54f6bf
Create Date: 2025-12-04 11:39:30.709506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f393c5deee'
down_revision = 'd8bebe54f6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
