"""add phone auth models

Revision ID: 234ff335896f
Revises: 098189bc4fff
Create Date: 2026-01-25 09:05:14.607629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '234ff335896f'
down_revision = '098189bc4fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_phone_number'), ['phone_number'], unique=False)

    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_redemptions_redemption_code'))

    op.drop_table('offer_redemptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_phone_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_phone_verified')
        batch_op.drop_column('phone_number')

    op.create_table('offer_redemptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('redemption_code', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('qr_token', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('redeemed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('offer_redemptions_company_id_fkey')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('offer_redemptions_offer_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('offer_redemptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('offer_redemptions_pkey')),
    sa.UniqueConstraint('qr_token', name=op.f('offer_redemptions_qr_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('offer_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_redemptions_redemption_code'), ['redemption_code'], unique=True)

    op.drop_table('sms_logs')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_phone_number'))

    op.drop_table('verification_codes')
    # ### end Alembic commands ###
