"""update users tbl

Revision ID: 28f073c96c25
Revises: f680e1031b1b
Create Date: 2026-01-10 12:33:31.823326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f073c96c25'
down_revision = 'f680e1031b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_settings_key_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_admin_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('membership_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('membership_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_settings_key'))
        batch_op.create_unique_constraint(batch_op.f('admin_settings_key_key'), ['key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
