"""update users tbl

Revision ID: 4b521a1f940f
Revises: b7d91a5f3c1a
Create Date: 2025-10-19 09:44:02.946105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b521a1f940f'
down_revision = 'b7d91a5f3c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('redemption_code', sa.String(length=12), nullable=False),
    sa.Column('qr_token', sa.String(length=36), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    with op.batch_alter_table('offer_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_redemptions_redemption_code'), ['redemption_code'], unique=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['owner_user_id'], ['id'])

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_permissions_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_permissions_permission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_company_id_companies'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_company_id_companies'), 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_permissions_permission_id_fkey'), 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_permissions_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('owner_user_id')

    with op.batch_alter_table('offer_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_redemptions_redemption_code'))

    op.drop_table('offer_redemptions')
    # ### end Alembic commands ###
