"""remove membership_level

Revision ID: 7096a3dabeaf
Revises: 28f073c96c25
Create Date: 2026-01-14 17:48:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7096a3dabeaf'
down_revision = '28f073c96c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('membership_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
