"""update models after changes

Revision ID: 96563a71f564
Revises: 9aee30b34166
Create Date: 2025-10-18 17:08:16.643378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96563a71f564'
down_revision = '9aee30b34166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_level', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('membership_level')

    # ### end Alembic commands ###
