"""Increase password_hash length to 512

Revision ID: 983923603431
Revises: 4b521a1f940f
Create Date: 2025-10-19 09:50:23.060965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983923603431'
down_revision = '4b521a1f940f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
