"""compony aproval

Revision ID: aaa3ef245f23
Revises: 5cb6d2330330
Create Date: 2025-10-21 11:25:30.564349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa3ef245f23'
down_revision = '5cb6d2330330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        op.add_column('companies', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
