"""add_offer_dates_and_image

Revision ID: c5e2f4e1833c
Revises: 21f393c5deee
Create Date: 2025-12-04 12:05:36.742935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e2f4e1833c'
down_revision = '21f393c5deee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
