"""create city and industry tbl

Revision ID: d8bebe54f6bf
Revises: 4a6601b273d4
Create Date: 2025-12-03 17:02:53.371898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bebe54f6bf'
down_revision = '4a6601b273d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'name', name='uq_lookup_choices_type_name')
    )
    with op.batch_alter_table('lookup_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_choices_list_type'), ['list_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lookup_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_choices_list_type'))

    op.drop_table('lookup_choices')
    # ### end Alembic commands ###
